version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:10.4.15'
    environment:
      MYSQL_ROOT_PASSWORD: 'olyseym2023logic'
      MYSQL_DATABASE: 'olyproxy'
      MYSQL_USER: 'oly'
      MYSQL_PASSWORD: 'olyseym2023logic'
    volumes:
      - ./data/mysql:/var/lib/mysql
